rhobs/konflux-coo

.gitmodules

Update submodules to point to current release branch for each ui-plugin. All ui-plugins should point to `release-0.3` except for `ui-logging` which should be `release-0.6` and except for `ui-monitoring` which remains unchanged.

OU-547: Update ui plugins release branch for COO 1.0.0

---

Dockerfile.prometheus

This is a temporary workaround to unblock konflux build pipeline until a valid rpm source for golang-github-prometheus-promu is available.
This will be only valid for non-hermetic builds.

Adjust prometheus v0.36.1 for konflux

---

Dockerfile.prometheus
Dockerfile.thanos

This PR changes the promu Dockerfiles for both prometheus and thanos so it uses the available pre-compiled binary rather than compiling it.
This will most likely be changed later on when moving to hermetic builds.

Use binary promu

---

.tekton/alertmanager-pull-request.yaml
.tekton/alertmanager-push.yaml
.tekton/cluster-observability-operator-bundle-pull-request.yaml
.tekton/cluster-observability-operator-bundle-push.yaml
.tekton/cluster-observability-operator-container-pull-request.yaml
.tekton/cluster-observability-operator-container-push.yaml
.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/coo-fbc-v4-17-push.yaml
.tekton/dashboards-console-plugin-0-3-pull-request.yaml
.tekton/dashboards-console-plugin-0-3-push.yaml
.tekton/distributed-tracing-console-plugin-0-3-pull-request.yaml
.tekton/distributed-tracing-console-plugin-0-3-push.yaml
.tekton/korrel8r-pull-request.yaml
.tekton/korrel8r-push.yaml
.tekton/logging-console-plugin-6-0-pull-request.yaml
.tekton/logging-console-plugin-6-0-push.yaml
.tekton/monitoring-console-plugin-0-3-pull-request.yaml
.tekton/monitoring-console-plugin-0-3-push.yaml
.tekton/obo-prometheus-operator-admission-webhook-pull-request.yaml
.tekton/obo-prometheus-operator-admission-webhook-push.yaml
.tekton/obo-prometheus-operator-prometheus-config-reloader-pull-request.yaml
.tekton/obo-prometheus-operator-prometheus-config-reloader-push.yaml
.tekton/obo-prometheus-operator-pull-request.yaml
.tekton/obo-prometheus-operator-push.yaml
.tekton/prometheus-pull-request.yaml
.tekton/prometheus-push.yaml
.tekton/thanos-pull-request.yaml
.tekton/thanos-push.yaml
.tekton/troubleshooting-panel-console-plugin-0-3-pull-request.yaml
.tekton/troubleshooting-panel-console-plugin-0-3-push.yaml

Per the Red Hat policy, the build pipeline must be updated to build source images. In order to do so, we need to change the build-source-image parameter in both pipelines (push and pull-request) default value to "true"

COO-541: Set up source build image

---

Dockerfile.thanos

This commit fixes the disallowed inherited tags violation for Thanos in COO.

Fix disallowed_inherited_labels for Thanos

---

Dockerfile.prometheus

This commit fixes the disallowed inherited tags violation for Prometheus in COO.

Fix disallowed_inherited_labels for Prometheus

---

renovate.json

The renovate.json file had an extra comma on it so it wasn't really being evaluated as a proper json.

Fix renovate json file

---

Dockerfile.alertmanager

This commit fixes the disallowed inherited tags violation for AlertManager in COO.

Add AlertManager description

---

Dockerfile.korrel8r

This commit fixes the disallowed inherited tags violation for korrel8r in COO.

Add korrel8r description

---

Dockerfile.ui-logging

This commit fixes the disallowed inherited tags violation for Console Plugin in COO.

Add console plugin description

---

Dockerfile.ui-distributed-tracing

This commit fixes the disallowed inherited tags violation for Distributed Tracing in COO.

Add distributed tracing description

---

Dockerfile.ui-troubleshooting-panel

This commit fixes the disallowed inherited tags violation for Troubleshooting Panel  in COO.

Add troubleshooting panel description

---

Dockerfile.ui-monitoring

This commit fixes the disallowed inherited tags violation for UI monitoring in COO.

Add ui monitoring description

---

Dockerfile.prom-op

This commit fixes the disallowed inherited tags violation for COO prometheus operator.

Coo prom op description

---

Dockerfile.ui-dashboards

This commit fixes the disallowed inherited tags violation for UI Dashboard in COO.

Add UI Dashboard description

---

.tekton/prometheus-pull-request.yaml
.tekton/prometheus-push.yaml

This commit adds several architectures for the prometheus component of cluster-observability-operator.

Enable multiarch builds for COO prometheus

---

Dockerfile.thanos

This commit fixes an issue in s390x builds for thanos, where running the build Makefile target would hit an issue.

Invoke promu directly in thanos builds

---

Dockerfile.alertmanager

Without this var, the build defaults on vendoring and fails.

Add missing go mod env var in alertmanager

---

.syft.yaml

This commit disables the syft github-actions cataloger, which has a bug breaking one of the pyxis steps in the Konflux release.

Disable syft github-actions cataloger

---

.tekton/korrel8r-push.yaml

We were missing an s in a pipeline leading to build failures.

fix korrel8r pipeline

---

.gitmodules

arm64 build is failing due a bug in prom-op version.
Update prom-op in order to fix it https://github.com/prometheus-operator/prometheus-operator/issues/7061

COO-571: bump prom-op to 0.78.1

---

.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/coo-fbc-v4-17-push.yaml

This commit modifies the 4.17 pull-request pipelineRun to trigger multi arch builds. It also fixes a missing change in the push pipelineRun
It changes the git-cone and buildah to the oci-ta variants while also still using a workspace due to the implementation of the fbc checks. It uses [1] as a sample.
[1] https://github.com/konflux-ci/olm-operator-konflux-sample/pull/65/files#
Signed-off-by: Daniel Mellado <dmellado@fedoraproject.org>

Add multiarch for fbc 4.17 pipelineRun in pull

---

.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/coo-fbc-v4-17-push.yaml

This commit fixes a few settings that were missing for fbc push multiarch. It also sets the hermetic builds to false as a default and changes the fbc pipeline trigger.

Fix gbc multiarch v17 push

---

.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/coo-fbc-v4-17-push.yaml

This commit disables the cap for pipeline triggering which was limiting it to edition on the catalog or the fbc Dockerfile.

COO-577: Disable cap on v4.17 pipeline trigger

---

.tekton/coo-fbc-v4-12-pull-request.yaml
.tekton/coo-fbc-v4-12-push.yaml
.tekton/coo-fbc-v4-13-pull-request.yaml
.tekton/coo-fbc-v4-13-push.yaml
.tekton/coo-fbc-v4-14-pull-request.yaml
.tekton/coo-fbc-v4-14-push.yaml
.tekton/coo-fbc-v4-15-pull-request.yaml
.tekton/coo-fbc-v4-15-push.yaml
.tekton/coo-fbc-v4-16-pull-request.yaml
.tekton/coo-fbc-v4-16-push.yaml
.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/coo-fbc-v4-17-push.yaml

This commit modifies the trigger for the catalog build so it applies only when there's a change in the actual catalog in order to avoid having it rebuilt on every commit.
Note that this would mean stopping seeing this in every regular commit CI, but that wasn't a real update but a rebuilt.  Currently there's no automation in place to have the catalogs updated per commit in the CI.

Build fbc catalog only on change in pipelines.

---

Dockerfile-4.15.catalog

This commit fixes the failure on the release's get_ocp_version task, which is getting an invalid parsing by the additional 0 on the Dockerfile.
Without this, it fails to parse the proper OCP version. The pattern does not match v4.15.0 because it expects a format like vX.Y

Fix 4.15 fbc release

---

.tekton/coo-fbc-v4-12-push.yaml

This commit fixes a bad indented 4_12 key issue on the 4_!2 push pipeline.

Fix 4.12 push tekton pipeline bad indentation

---

renovate.json

This PR adds an exception to the registries which will update the fbc Dockerfiles, which is unwanted. Without this, fbc Dockerfile will receive PR trying to update them to newer versions of OpenShift.

Ignore fbc catalog files in mintmaker

---

.tekton/alertmanager-pull-request.yaml
.tekton/cluster-observability-operator-container-pull-request.yaml
.tekton/coo-fbc-v4-12-pull-request.yaml
.tekton/coo-fbc-v4-13-pull-request.yaml
.tekton/coo-fbc-v4-14-pull-request.yaml
.tekton/coo-fbc-v4-15-pull-request.yaml
.tekton/coo-fbc-v4-16-pull-request.yaml
.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/dashboards-console-plugin-0-3-pull-request.yaml
.tekton/distributed-tracing-console-plugin-0-3-pull-request.yaml
.tekton/korrel8r-pull-request.yaml
.tekton/logging-console-plugin-6-0-pull-request.yaml
.tekton/monitoring-console-plugin-0-3-pull-request.yaml
.tekton/obo-prometheus-operator-admission-webhook-pull-request.yaml
.tekton/obo-prometheus-operator-prometheus-config-reloader-pull-request.yaml
.tekton/obo-prometheus-operator-pull-request.yaml
.tekton/prometheus-pull-request.yaml
.tekton/thanos-pull-request.yaml
.tekton/troubleshooting-panel-console-plugin-0-3-pull-request.yaml

This commit disables both s390x and ppc64le files in konflux-coo tekton pipelines in order for https://github.com/rhobs/konflux-coo/pull/413 to pass

Disable s390x and ppc64le build on tekton pr files

---

.tekton/coo-fbc-v4-18-push.yaml

This commit formats the coo-fbc-v4-18-push.yaml file in order to keep
the same style as the other ones.
Signed-off-by: Daniel Mellado <dmellado@fedoraproject.org>

Format 4.18 fbc push yaml file

---

bundle-patches/render_templates

Use the newer Pyxis image paths instead of Quay ones.
I've not made changes to the Quay paths that these images get pushed to, as that should eventually be irrelevant since customers will end up consuming from the production registry, while QE would use the staging one (and the fact that I want to keep the blast radius to a minimum). This is also in-line with what we have seen in [`rhosdt`](https://github.com/os-observability/konflux-tempo/blob/b85647809443699238765ce20e9b55131565023c/.tekton/tempo-opa-push.yaml#L37) as well.

fix: Use Pyxis image paths

---

.gitmodules
Dockerfile.perses-operator

https://issues.redhat.com/browse/OU-453
Add perses-operator as a component of the COO Konflux application. 
1.  Add perses-operator submodule and update `.gitmodule` to point at perses/perses-operator release branch `release-coo-1.1`
-  Ran `$ git submodule add https://github.com/perses/perses-operator`
2. Add `Dockerfiler.perses-operator` for Konflux Pipeline to build the image

OU-453: Add perses-operator

---

.tekton/coo-fbc-v4-12-pull-request.yaml
.tekton/coo-fbc-v4-12-push.yaml
.tekton/coo-fbc-v4-13-pull-request.yaml
.tekton/coo-fbc-v4-13-push.yaml
.tekton/coo-fbc-v4-14-pull-request.yaml
.tekton/coo-fbc-v4-14-push.yaml
.tekton/coo-fbc-v4-15-pull-request.yaml
.tekton/coo-fbc-v4-15-push.yaml
.tekton/coo-fbc-v4-16-pull-request.yaml
.tekton/coo-fbc-v4-16-push.yaml
.tekton/coo-fbc-v4-17-pull-request.yaml
.tekton/coo-fbc-v4-17-push.yaml
.tekton/coo-fbc-v4-18-pull-request.yaml
.tekton/coo-fbc-v4-18-push.yaml
.tekton/coo-fbc-v4-19-pull-request.yaml
.tekton/coo-fbc-v4-19-push.yaml
.tekton/images-mirror-set.yaml

All products building FBC fragments in Konflux are requested to merge this change irrespective of whether the product is intended for FIPS mode or not.
Beginning March 1, 2025, the fbc-fips-task is going to be a required task in the Konflux
pipeline. This means, your release will be blocked if this task is not present in your pipeline run.
The answer is yes. If your product is not designed to operate in FIPS mode, the task will identify that and will
automatically skip the FIPS scan. However, the task still needs to be a part of your pipeline.
* This commit adds the fbc-fips-check task to your pipeline yaml.
* It also adds a file named `images-mirror-set.yaml` to your `.tekton` directory with an example in it. This file is an `ImageDigestMirrorSet` required by the task to access any …

RELEASE BLOCKER(March 1, 2025): add fbc-fips-check task to FBC pipeline
