- .gitmodules
- Dockerfile.thanos
This commit adds thanos Dockerfile to the coo konflux repository.
> COO-390: Add thanos component

- .gitmodules
> Revert "chore(deps): update ui-distributed-tracing digest to 595e7a1"

- Dockerfile.alertmanager
- Dockerfile.bundle
- Dockerfile.korrel8r
- Dockerfile.obo
- Dockerfile.prom-op
- Dockerfile.prometheus
- Dockerfile.prometheus-config-reloader
- Dockerfile.thanos
This commits bumps the ubi8 image in all Dockerfiles using it to ubi8/ubi-minimal:8.10-1130
> Bump ubi-minimal/8 base image

- .gitmodules
> Revert "chore(deps): update prometheus digest to fb933ae"

- releases/release-1_0-stage.yaml
This commit fixes the indentation and adds a valid issue number for the RHBA release example.
> Fix release example

- Dockerfile.alertmanager
- Dockerfile.bundle
- Dockerfile.korrel8r
- Dockerfile.obo
- Dockerfile.prom-op
- Dockerfile.prometheus
- Dockerfile.prometheus-config-reloader
- Dockerfile.thanos
- Dockerfile.ui-dashboards
- Dockerfile.ui-distributed-tracing
- Dockerfile.ui-logging
- Dockerfile.ui-monitoring
- Dockerfile.ui-troubleshooting-panel
This reverts commit 99a837e079ff5b2b6e6d9c29dc6cf209f880724e.
> Revert "rebuild"

- bundle-patches/render_templates
Fixes: https://issues.redhat.com/browse/COO-569
> fix bundle containerImage metadata

- Dockerfile.obo
Fixes: https://issues.redhat.com/browse/COO-194
> install rsync, tar, xz for must-gather

- .tekton/monitoring-console-plugin-0-3-push.yaml
- .tekton/obo-prometheus-operator-push.yaml
Gets rid of the endless loop of updates via the bundle
> fix pipeline triggers for mon console and prometheus-operator

- .tekton/monitoring-console-plugin-0-3-push.yaml
- .tekton/obo-prometheus-operator-admission-webhook-push.yaml
- .tekton/obo-prometheus-operator-push.yaml
This commit changes triggers set to happen in pull request to the proper push.
> Fix tekton pipelines wrong triggers

- bundle-patches/render_templates
> manual bump for admission-webhook

- .tekton/coo-fbc-v4-12-push.yaml
- .tekton/coo-fbc-v4-13-push.yaml
- .tekton/coo-fbc-v4-14-push.yaml
- .tekton/coo-fbc-v4-15-push.yaml
- .tekton/coo-fbc-v4-16-push.yaml
- .tekton/coo-fbc-v4-17-push.yaml
This commit fixes a typo in the cel expression for fbc push tekton pipelines.
> Fix fbc cel pipeline expression

- .tekton/dashboards-console-plugin-0-3-pull-request.yaml
- .tekton/dashboards-console-plugin-0-3-push.yaml
Trigger ui-dashboard after delete and create component to get new url https://issues.redhat.com/browse/COO-605
> Trigger ui-dashboard after delete and create component

- .tekton/troubleshooting-panel-console-plugin-0-3-pull-request.yaml
- .tekton/troubleshooting-panel-console-plugin-0-3-push.yaml
> Modify ref troubleshooting-panel

- .tekton/korrel8r-pull-request.yaml
- .tekton/korrel8r-push.yaml
> Modify korrel8r image

- .tekton/logging-console-plugin-6-0-pull-request.yaml
- .tekton/logging-console-plugin-6-0-push.yaml
> Modify ref logging console

- .tekton/distributed-tracing-console-plugin-0-3-pull-request.yaml
- .tekton/distributed-tracing-console-plugin-0-3-push.yaml
> Modify distributed-tracing image name

- .tekton/prometheus-pull-request.yaml
- .tekton/prometheus-push.yaml
> Modify ref prometheus

- Dockerfile.alertmanager
This reverts commit b0e73792851aca55b6a0e1bd09b9cd2807233153.
> Revert "DNM: nudge debugging"

- Dockerfile.ui-distributed-tracing
- Dockerfile.ui-troubleshooting-panel
distributed-tracing-console-plugin-0-3-rhel9
troubleshooting-panel-console-plugin-0-3-rhel9
> trigger nudges on components
